// Bundles the canonical authoring source files into a generated TypeScript
// module the filesystem-less OpenRouter action can import (ADR 0014, PRD
// "Bundled assets"). The `teach` skill's instructions and the shared lesson
// design-system partials are the single source of truth; this mirrors them into
// `convex/authoringAssets.generated.ts` so the action's prompt + HTML wrap can't
// silently drift from the skill. Regenerate with `pnpm bundle:authoring`.
//
// Deterministic: given identical sources it emits byte-identical output (no
// timestamps, fixed key order), and it only writes when the content changed — so
// re-running on unchanged sources is a no-op and CI can assert the file is fresh.
import { readFileSync, writeFileSync } from "node:fs";

// The teach instructions, in the order they compose into the system prompt. Paths
// resolve against the repo root (`.agents/skills/teach/` is the real skill dir;
// `.claude/skills` symlinks into it).
//
// Ownership matters here. `.agents/skills/teach/` is owned by the skills CLI, and
// `npx skills update` deletes from it: `e242e50` (2026-08-27) removed `AUTHORING.md`
// upstream and left this bundler unable to start for eleven days. So the authoring
// *contract*, the one doc that is this repo's lesson mechanics rulebook rather than
// upstream teaching judgement, now lives in `lessons/` beside the template and
// partials it describes, where the CLI cannot reach it. The five below are the live
// skill: copying them here would create exactly the drift this file exists to
// prevent, so they stay pointed at the skill and `bundleAuthoringAssets` refuses
// loudly if the CLI takes another one.
const TEACH_DOCS = [
  ".agents/skills/teach/SKILL.md",
  "lessons/AUTHORING.md",
  ".agents/skills/teach/MISSION-FORMAT.md",
  ".agents/skills/teach/LEARNING-RECORD-FORMAT.md",
  ".agents/skills/teach/GLOSSARY-FORMAT.md",
  ".agents/skills/teach/RESOURCES-FORMAT.md",
] as const;
const HEAD_PARTIAL = "lessons/_partials/head.html";
const FOOT_PARTIAL = "lessons/_partials/foot.html";
const REFERENCE_HEAD_PARTIAL = "lessons/_partials/reference-head.html";

export const OUTPUT = "convex/authoringAssets.generated.ts";

// Pure renderer — the whole determinism guarantee lives here, so it's unit-tested
// without touching the filesystem. `docs` are the verbatim teach files in order;
// `head`/`foot` the verbatim partials. Output escapes every string with
// JSON.stringify, so any backticks/${} in the sources are inert.
export function renderAssetsModule(
  docs: { rel: string; content: string }[],
  head: string,
  foot: string,
  referenceHead: string,
): string {
  // The composed system prompt: each doc verbatim, under a `# === <path> ===`
  // header so the model sees the boundaries. Headers are derived from the fixed
  // paths, so the composition stays deterministic.
  const instructions = docs.map((d) => `# === ${d.rel} ===\n\n${d.content.trim()}`).join("\n\n");
  return `// GENERATED by scripts/bundle-authoring-assets.ts — do not edit by hand.
// Run \`pnpm bundle:authoring\` to regenerate from the teach skill + lesson partials.
/* eslint-disable */

// The teach skill's instructions (SKILL + AUTHORING + *-FORMAT), verbatim and
// composed in prompt order — the OpenRouter authoring system prompt.
export const TEACH_INSTRUCTIONS = ${JSON.stringify(instructions)};

// The shared lesson design-system head + quiz-feedback foot (lessons/_partials/),
// verbatim — wrapped around the model's lean fragment at publish time.
export const LESSON_HEAD = ${JSON.stringify(head.trim())};
export const LESSON_FOOT = ${JSON.stringify(foot.trim())};

// The shared reference design system (lessons/_partials/reference-head.html),
// verbatim — wrapped around the model's lean reference fragment.
export const REFERENCE_HEAD = ${JSON.stringify(referenceHead.trim())};
`;
}

// Reads one source, and names it when it is gone. `readFileSync`'s own ENOENT
// reports `open '<absolute path>'` and nothing about why the repo wanted that file,
// which is what made the 2026-08-27 breakage read as an unrelated crash.
export function readSource(rel: string): string {
  try {
    return readFileSync(rel, "utf8");
  } catch (e) {
    throw new Error(
      `bundle:authoring cannot read the authoring source "${rel}". ` +
        `If it lives under .agents/skills/, the skills CLI has deleted it upstream: ` +
        `recover the content, move it somewhere this repo owns (as lessons/AUTHORING.md is), ` +
        `and repoint TEACH_DOCS. Cause: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
}

// The bundle end to end: read every source off disk and render the module. This is
// the interface the test drives, so "the bundler still runs" and "the generated file
// is fresh" become one assertion instead of a script nothing ever executes.
export function bundleAuthoringAssets(teachDocs: readonly string[] = TEACH_DOCS): string {
  const docs = teachDocs.map((rel) => ({ rel, content: readSource(rel) }));
  return renderAssetsModule(
    docs,
    readSource(HEAD_PARTIAL),
    readSource(FOOT_PARTIAL),
    readSource(REFERENCE_HEAD_PARTIAL),
  );
}

// Runnable only when invoked directly (not when imported by a test).
if (process.argv[1] && process.argv[1].endsWith("bundle-authoring-assets.ts")) {
  const next = bundleAuthoringAssets();

  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    /* first run — no existing file */
  }
  if (current === next) {
    console.log(`${OUTPUT} already up to date.`);
  } else {
    writeFileSync(OUTPUT, next);
    console.log(`Wrote ${OUTPUT} from ${TEACH_DOCS.length} teach docs + 3 partials.`);
  }
}
