// Bundles the canonical authoring source files into a generated TypeScript
// module the filesystem-less OpenRouter action can import (ADR 0014, PRD
// "Bundled assets"). The `teach` skill's instructions and the shared lesson
// design-system partials are the single source of truth; this mirrors them into
// `convex/authoringAssets.generated.ts` so the action's prompt + HTML wrap can't
// silently drift from the skill. Regenerate with `pnpm bundle:authoring`.
//
// Deterministic: given identical sources it emits byte-identical output (no
// timestamps, fixed key order), and it only writes when the content changed — so
// re-running on unchanged sources is a no-op and CI can assert the file is fresh.
import { readFileSync, writeFileSync } from "node:fs";

// The teach instructions, in the order they compose into the system prompt. Paths
// resolve against the repo root (`.agents/skills/teach/` is the real skill dir;
// `.claude/skills` symlinks into it).
const TEACH_DOCS = [
  ".agents/skills/teach/SKILL.md",
  ".agents/skills/teach/AUTHORING.md",
  ".agents/skills/teach/MISSION-FORMAT.md",
  ".agents/skills/teach/LEARNING-RECORD-FORMAT.md",
  ".agents/skills/teach/GLOSSARY-FORMAT.md",
  ".agents/skills/teach/RESOURCES-FORMAT.md",
] as const;
const HEAD_PARTIAL = "lessons/_partials/head.html";
const FOOT_PARTIAL = "lessons/_partials/foot.html";

const OUTPUT = "convex/authoringAssets.generated.ts";

// Pure renderer — the whole determinism guarantee lives here, so it's unit-tested
// without touching the filesystem. `docs` are the verbatim teach files in order;
// `head`/`foot` the verbatim partials. Output escapes every string with
// JSON.stringify, so any backticks/${} in the sources are inert.
export function renderAssetsModule(
  docs: { rel: string; content: string }[],
  head: string,
  foot: string,
): string {
  // The composed system prompt: each doc verbatim, under a `# === <path> ===`
  // header so the model sees the boundaries. Headers are derived from the fixed
  // paths, so the composition stays deterministic.
  const instructions = docs.map((d) => `# === ${d.rel} ===\n\n${d.content.trim()}`).join("\n\n");
  return `// GENERATED by scripts/bundle-authoring-assets.ts — do not edit by hand.
// Run \`pnpm bundle:authoring\` to regenerate from the teach skill + lesson partials.
/* eslint-disable */

// The teach skill's instructions (SKILL + AUTHORING + *-FORMAT), verbatim and
// composed in prompt order — the OpenRouter authoring system prompt.
export const TEACH_INSTRUCTIONS = ${JSON.stringify(instructions)};

// The shared lesson design-system head + quiz-feedback foot (lessons/_partials/),
// verbatim — wrapped around the model's lean fragment at publish time.
export const LESSON_HEAD = ${JSON.stringify(head.trim())};
export const LESSON_FOOT = ${JSON.stringify(foot.trim())};
`;
}

// Runnable only when invoked directly (not when imported by a test).
if (process.argv[1] && process.argv[1].endsWith("bundle-authoring-assets.ts")) {
  const docs = TEACH_DOCS.map((rel) => ({ rel, content: readFileSync(rel, "utf8") }));
  const head = readFileSync(HEAD_PARTIAL, "utf8");
  const foot = readFileSync(FOOT_PARTIAL, "utf8");
  const next = renderAssetsModule(docs, head, foot);

  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    /* first run — no existing file */
  }
  if (current === next) {
    console.log(`${OUTPUT} already up to date.`);
  } else {
    writeFileSync(OUTPUT, next);
    console.log(`Wrote ${OUTPUT} from ${docs.length} teach docs + 2 partials.`);
  }
}
